#!/bin/sh

echo "Dump location (or enter 'r' for USB root): "
read loc

if [ $loc = "r" ]
then
    loc=/mnt/us
    echo "Using USB root."
else
    echo "Using $loc"
fi

echo "Would you like to echo to stdout too? (y/n): "
read verb

mntroot rw

if [ $verb = "y" ]
then
    for file in $(find /); do echo $file; echo $file >> $loc/dump.txt; done
else
    echo "Starting..."
    for file in $(find /); do echo $file >> $loc/dump.txt; done
fi

echo "FS dump saved to $loc/dump.txt"